artifact_location: /workspaces/AI_DATA_ANALYSIS_/src/Module 10/Best Practices & Industry
  Case Studies/my_mlruns/0
creation_time: 1746788190177
experiment_id: '0'
last_update_time: 1746788190177
lifecycle_stage: active
name: Default
