artifact_uri: /workspaces/AI_DATA_ANALYSIS_/src/Module 10/Best Practices & Industry
  Case Studies/my_mlruns/0/30f345a10d934de6bae51225cf92b0e2/artifacts
end_time: 1746788400805
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 30f345a10d934de6bae51225cf92b0e2
run_name: defiant-goat-184
run_uuid: 30f345a10d934de6bae51225cf92b0e2
source_name: ''
source_type: 4
source_version: ''
start_time: 1746788396398
status: 3
tags: []
user_id: vscode
