artifact_uri: /workspaces/AI_DATA_ANALYSIS_/src/Module 10/Best Practices & Industry
  Case Studies/my_mlruns/0/e1226d11199a44679cbcd92cb6aabf10/artifacts
end_time: 1746788871758
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e1226d11199a44679cbcd92cb6aabf10
run_name: mercurial-seal-733
run_uuid: e1226d11199a44679cbcd92cb6aabf10
source_name: ''
source_type: 4
source_version: ''
start_time: 1746788867504
status: 3
tags: []
user_id: vscode
